name = "toronto-balcony-cleaners"
compatibility_date = "2024-09-23"
main = "src/worker.js"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
BUSINESS_EMAIL = "bookings@torontobalconycleaners.com"
FROM_EMAIL = "noreply@torontobalconycleaners.com"
